import { Product, Testimonial } from './types';

export const CATEGORIES = ['All', 'Men', 'Women', 'Accessories', 'Sale'];

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Classic Oxford Shirt',
    price: 89.99,
    category: 'Men',
    image: '/images/product-1.jpg',
    description: 'Timeless button-down shirt perfect for any occasion',
    rating: 4.5,
    reviews: 128,
  },
  {
    id: '2',
    name: 'Premium Denim Jeans',
    price: 129.99,
    category: 'Men',
    image: '/images/product-2.jpg',
    description: 'Comfortable and stylish denim for everyday wear',
    rating: 4.8,
    reviews: 234,
  },
  {
    id: '3',
    name: 'Flowing Linen Dress',
    price: 149.99,
    category: 'Women',
    image: '/images/product-3.jpg',
    description: 'Elegant linen dress perfect for summer',
    rating: 4.7,
    reviews: 189,
  },
  {
    id: '4',
    name: 'Cozy Sweater',
    price: 119.99,
    category: 'Women',
    image: '/images/product-4.jpg',
    description: 'Soft and warm sweater for chilly days',
    rating: 4.6,
    reviews: 156,
  },
  {
    id: '5',
    name: 'Leather Crossbody Bag',
    price: 199.99,
    category: 'Accessories',
    image: '/images/product-5.jpg',
    description: 'Premium leather bag for everyday use',
    rating: 4.9,
    reviews: 267,
  },
  {
    id: '6',
    name: 'Designer Sunglasses',
    price: 159.99,
    category: 'Accessories',
    image: '/images/product-6.jpg',
    description: 'UV-protective sunglasses with style',
    rating: 4.4,
    reviews: 98,
  },
  {
    id: '7',
    name: 'Premium T-Shirt',
    price: 45.99,
    category: 'Sale',
    image: '/images/product-7.jpg',
    description: 'High-quality cotton t-shirt',
    rating: 4.5,
    reviews: 145,
  },
  {
    id: '8',
    name: 'Casual Blazer',
    price: 199.99,
    category: 'Men',
    image: '/images/product-8.jpg',
    description: 'Versatile blazer for professional and casual settings',
    rating: 4.7,
    reviews: 203,
  },
  {
    id: '9',
    name: 'Athletic Leggings',
    price: 89.99,
    category: 'Women',
    image: '/images/product-9.jpg',
    description: 'Comfortable leggings for workouts and everyday wear',
    rating: 4.8,
    reviews: 312,
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: '1',
    name: 'Sarah Mitchell',
    role: 'Fashion Blogger',
    content:
      'Amazing quality and style! The customer service is exceptional and shipping was incredibly fast.',
    avatar: '/images/avatar-1.jpg',
    rating: 5,
  },
  {
    id: '2',
    name: 'James Chen',
    role: 'Business Professional',
    content:
      'Perfect for my work wardrobe. The fabrics are premium and the fit is exactly as expected.',
    avatar: '/images/avatar-2.jpg',
    rating: 5,
  },
  {
    id: '3',
    name: 'Emma Johnson',
    role: 'Lifestyle Enthusiast',
    content: 'Love the variety and the prices are competitive. Highly recommend to everyone!',
    avatar: '/images/avatar-3.jpg',
    rating: 4,
  },
  {
    id: '4',
    name: 'David Williams',
    role: 'Style Consultant',
    content:
      'Excellent collection with great attention to detail. The website is easy to navigate and checkout is smooth.',
    avatar: '/images/avatar-4.jpg',
    rating: 5,
  },
];